# Array Operations

In [4]:
import numpy as np
arr=np.arange(11)
print(arr)
print("basic Slicing: ",arr[2:6])
print("or Slicing: ",arr[2:6:2])
print("or Slicing: ",arr[-2:-6:-2])


[ 0  1  2  3  4  5  6  7  8  9 10]
basic Slicing:  [2 3 4 5]
or Slicing:  [2 4]
or Slicing:  [9 7]


# 2D Array Slicing

In [5]:
arr2D=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr2D[1][1])
print("Entire row:\n",arr2D[1])
print("Entire colomn:\n",arr2D[:,1])

5
Entire row:
 [4 5 6]
Entire colomn:
 [2 5 8]


In [45]:
# numb=3
# total=""
# while numb:
#     rem=numb%2
#     total+=str(rem)
#     numb//=2
# print(int(total[::-1]))   // decimal to binary


# hollow Squre

# rows=6
# for i in range(rows):
#     if not i or i==rows-1:
#         print("*"*rows,end="")
#     else:
#         print("*",end="")
#         print(" "*(rows-2),end="")
#         print("*",end="")
#     print()


# binNum=10101110011
# temp=binNum
# i,sumnum=0,0
# while binNum:
#     rem=binNum%10
#     sumnum+=(rem*pow(2,i))
#     i+=1
#     binNum//=10
# print(f"Demical form of binary number {temp} is: {sumnum}")

nthTerm=7

def fibo(nthTerm):
    # storageFibo={1:0,
    #              2:1}
    # if nthTerm in storageFibo:
    #     return storageFibo[nthTerm]
    # else:
    #     pass
    if nthTerm==1:
        return 0
    elif nthTerm==2:
        return 1
    else:
        return fibo(nthTerm-1)+fibo(nthTerm-2)
print(fibo(nthTerm))

8
