# Array Operations

In [ ]:
import numpy as np
arr=np.arange(11)
print(arr)
print("basic Slicing: ",arr[2:6])
print("or Slicing: ",arr[2:6:2])
print("or Slicing: ",arr[-2:-6:-2])


[ 0  1  2  3  4  5  6  7  8  9 10]
basic Slicing:  [2 3 4 5]
or Slicing:  [2 4]
or Slicing:  [9 7]


# 2D Array Slicing

In [ ]:
arr2D=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr2D[1][1])
print("Entire row:\n",arr2D[1])
print("Entire colomn:\n",arr2D[:,1]) # : for all rows & ,1 for 1st column

5
Entire row:
 [4 5 6]
Entire colomn:
 [2 5 8]


# Sorting 


In [ ]:
unsortedArr=np