Shift + enter to generate new markdown
 where as CTRL + enter to escape from a markdown
and we use for new code line 
Use # then write to make markdowns big like below number of # == bigger lines

## NUMPY array & basics

In [1]:
import numpy as np


## Creating Array from list

In [4]:
arr1D=np.array([1, 2, 3, 4, 5])
print("1D Array is:", arr1D)

# array only supports Similar data types by defination 

arr2D=np.array([[1,2,3],[4,5,6]])
print("2D array is: \n", arr2D)

1D Array is: [1 2 3 4 5]
2D array is: 
 [[1 2 3]
 [4 5 6]]


## List Vs Arrays


In [7]:
myList=[1,2,3,4]
myArr=np.array([1,2,3,4])

print("list Multiply ny 2: ", myList*2)
print("Array Multiply ny 2: ", myArr*2)

list Multiply ny 2:  [1, 2, 3, 4, 1, 2, 3, 4]
Array Multiply ny 2:  [2 4 6 8]


# Creating Array from Scratch

In [22]:
#  Zeros is used to print 0 marrix values inside () denotes the row & colomns
zeroMatrix=np.zeros((4,5))
print(zeroMatrix)
print()
print()   

onesArray=np.ones((3,5))
print(onesArray)
print()
print()  
fullArray=np.full((2,2),7 ) # makes a (_*_) matrices with the valu ouside tuple  
print(fullArray)

print(np.random.random((2,4))) # put random values in side a (_ * _) matrix (vales are usually in 0-1) 

sequenceArr=np.arange(1,12,2)
print(sequenceArr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[7 7]
 [7 7]]
[[0.84920989 0.77168985 0.03419943 0.36761051]
 [0.96798655 0.58805497 0.7124008  0.18396884]]
[ 1  3  5  7  9 11]


## Vector, Matrix and Tensor


In [25]:
vector=np.array([1,2,3])  # vectors are usually 1D arrays
matrix=np.array([[1,2,3]
                 ,[4,5,6]]) # # matrix is 2D array
tensor=np.array([[[1,2]
                  ,[3,4]]
                 ,[[5,6],
                   [7,8]]]) # tensor is 3D array

print("Vector: ", vector)
print("Matrix: \n", matrix)
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# array Properties


In [28]:
Arr2Dim=np.array([[1,2,3],
                  [4,5,6]])

print("Array 2D shape: ", Arr2Dim.shape)  # gives the shape of the array
print("Array 2D size: ", Arr2Dim.size)    # gives the size of the array
print("Array 2D dtype: ", Arr2Dim.dtype)  # gives the data type of the array
print("Array 2D Dimention : ", Arr2Dim.ndim)  # gives the Dimention of the array


Array 2D shape:  (2, 3)
Array 2D size:  6
Array 2D dtype:  int32
Array 2D Dimention :  2


## Array Reshaping


In [ ]:
arr=np.arange(15)
print("Array is : ", arr)

reshapedArr=arr.reshape ([3,5])  # reshaping the array to 3 rows and 5 column
print("Reshaped Array is : \n", reshapedArr)

flattenedArr=reshapedArr.flatten()  # flattening the array to 1D
print("Flattened Array is : ", flattenedArr)

# ravel returns view not copy of the array
reveled=reshapedArr.ravel()  # raveling the array to 1D
print("Raveled Array is : ", reveled)

# transpose mattrix: it is used to swap the rows and columns of the array so that the rows become columns and columns become rows
transposedArr=reshapedArr.T  # transposing the array
print("Transposed Array is : \n", transposedArr)

Array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped Array is : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Flattened Array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Raveled Array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Transposed Array is : 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
